application_certificats_certificatscenter:
    resource: "@ApplicationCertificatsBundle/Resources/config/routing/certificatscenter.yml"
    prefix:   /certificatscenter

application_certificats_certificatscenter_download:
    resource: "@ApplicationCertificatsBundle/Resources/config/routing/certificatsdownload.yml"
    prefix:   /certificatscenterd
    