application_certificats_certificatscenter:
    resource: "@ApplicationCertificatsBundle/Resources/config/routing/certificatscenter.yml"
    prefix:   /certificatscenter

application_certificats_docs:
    resource: "@ApplicationCertificatsBundle/Resources/config/routing/certificatsfiles.yml"
    prefix:   /certificatsdocs
    