docchangements:
    pattern:  /
    defaults: { _controller: "ApplicationCertificatsBundle:Docchangements:index" }

docchangements_show:
    pattern:  /{id}/show
    defaults: { _controller: "ApplicationCertificatsBundle:Docchangements:show" }

docchangements_new:
    pattern:  /new
    defaults: { _controller: "ApplicationCertificatsBundle:Docchangements:new" }

docchangements_create:
    pattern:  /create
    defaults: { _controller: "ApplicationCertificatsBundle:Docchangements:create" }
    requirements: { _method: post }

docchangements_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ApplicationCertificatsBundle:Docchangements:edit" }

docchangements_update:
    pattern:  /{id}/update
    defaults: { _controller: "ApplicationCertificatsBundle:Docchangements:update" }
    requirements: { _method: post }

docchangements_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ApplicationCertificatsBundle:Docchangements:delete" }
    requirements: { _method: post }
