<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\EservicesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class EproduitHistoryRepository extends EntityRepository {

    public function myFindAll($user_id,$isDemande=0) {

        $query = $this->createQueryBuilder('a')
                ->where('a.demandeur = :demandeur')
                ->andWhere('a.isDemande = :typedemande')
                ->setParameter('demandeur', $user_id)
                ->setParameter('typedemande', $isDemande)
                ->leftJoin('a.idStatus', 'd')
                ->add('orderBy', 'a.id DESC')
                ->getQuery();
        return $query;
    }

    public function myFindOtherForme($user_id) {

        $query = $this->createQueryBuilder('a')
                ->where('a.demandeur <> :demandeur')
                ->setParameter('demandeur', $user_id)
                ->andWhere(':theuser MEMBER OF a.idusers')
                ->setParameter('theuser', $user_id)
                ->add('orderBy', 'a.id DESC')
                ->getQuery();
        return $query;
    }

    public function myFindOtherAll($user_id) {

        $query = $this->createQueryBuilder('a')
                ->where('a.demandeur <> :demandeur')
                ->setParameter('demandeur', $user_id)
                ->add('orderBy', 'a.id DESC')
                ->getQuery();
        return $query;
    }

    public function findproposal($user_id = null) {
        /*    $query = $this->createQueryBuilder('a')
          ->where('a.demandeur = :demandeur')
          ->setParameter('demandeur', $user_id)
          ->leftJoin('a.idStatus', 'd')
          ->where('c. IS NOT NULL');
          ->add('orderBy', 'a.id DESC')

          //->orderBy('p.price', 'ASC')
          ->getQuery();
          return $query; */
        /*  return $this->createQueryBuilder('a')
          ->leftJoin('a.idProjet', 'b')
          ->leftJoin('a.idStatus', 'd')
          ->leftJoin('a.demandeur', 'c')
          ->add('orderBy', 'a.id DESC')
          //   ->leftJoin('a.demandeur', 'c')
          ->getQuery(); */
    }

}