calendar_adesignajax:
    methods: POST|GET
    pattern:  /adesignajax
    defaults: { _controller: "ApplicationChangementsBundle:AdesignCalendar:loadjqCalendar" }
    options:
        expose: true

calendar_adesignajax_changements:
    methods: POST|GET
    pattern:  /adesignajaxchangements
    defaults: { _controller: "ApplicationChangementsBundle:AdesignCalendar:loadjqCalendarChangements" }
    options:
        expose: true  
        
calendar_dropajax:
    methods: POST|GET
    pattern:  /updateajax
    defaults: { _controller: "ApplicationChangementsBundle:AdesignCalendar:updatejqCalendar" }
    options:
        expose: true
        


wdcalendar_indexadesignchangement:
    pattern:  /adesignchangements
    defaults: { _controller: "ApplicationChangementsBundle:AdesignCalendar:indexadesignchangements" }
    
wdcalendar_indexadesign:
    pattern:  /adesign
    defaults: { _controller: "ApplicationChangementsBundle:AdesignCalendar:indexadesign" }
    
     
 
