 
#---------------------------------------------------------------
# Changements Indexes: fanta par defaut
#--------------------------------------------------------------- 

wdcalendar_index:
    pattern:  /
    defaults: { _controller: "ApplicationChangementsBundle:Calendar:index" }
    methods: POST|GET
    
wdcalendar_indexall:
    pattern:  /all
    defaults: { _controller: "ApplicationChangementsBundle:Calendar:indexall" }
    
calendar_adesignajax:
    methods: POST|GET
    pattern:  /adesignajax
    defaults: { _controller: "ApplicationChangementsBundle:Calendar:loadjqCalendar" }
    options:
        expose: true
   
calendar_dropajax:
    methods: POST|GET
    pattern:  /updateajax
    defaults: { _controller: "ApplicationChangementsBundle:Calendar:updatejqCalendar" }
    options:
        expose: true
        
calendar_ajax:
    methods: POST|GET
    pattern:  /wdcalajax
    defaults: { _controller: "ApplicationChangementsBundle:Calendar:datafeed" }
    options:
        expose: true
 
wdcalendar_indexadesign:
    pattern:  /adesign
    defaults: { _controller: "ApplicationChangementsBundle:Calendar:indexadesign" }
    
    
calendar_showXhtml:
    pattern:  /{id}/showxhtml
    defaults: { _controller: "ApplicationChangementsBundle:Calendar:showXhtml" }
    methods: POST|GET
    options:
        expose: true
 

calendar_create:
    pattern:  /new
    defaults: { _controller: "ApplicationChangementsBundle:Calendar:new" }
    options:
        expose: true
  
calendar_edit:
    methods: POST|GET
    pattern:  /{id}/wdcaledit
    defaults: { _controller: "ApplicationChangementsBundle:Calendar:editwd" }
    options:
        expose: true
 
 
 
