 
#---------------------------------------------------------------
# Changements Indexes: fanta par defaut
#--------------------------------------------------------------- 

wdcalendar_index:
    pattern:  /
    defaults: { _controller: "ApplicationChangementsBundle:Calendar:index" }
    methods: POST|GET
    
    
  
calendar_ajax:
    methods: POST|GET
    pattern:  /wdcalajax
    defaults: { _controller: "ApplicationChangementsBundle:Calendar:datafeed" }
    options:
        expose: true
        
        
calendar_edit:
    methods: POST|GET
    pattern:  /wdcaledit
    defaults: { _controller: "ApplicationChangementsBundle:Calendar:editwdAction" }
    options:
        expose: true
 
 
 
