#---------------------------------------------------------------
# Appels Ajax
#---------------------------------------------------------------
ajax_nom:
    pattern:  /ajaxnom
    methods: POST|GET
    defaults: { _controller: "ApplicationChangementsBundle:Changements:NomAjax" }
  
ajax_checkuser:
    pattern:  /ajaxusercheck
    methods: POST|GET
    defaults: { _controller: "ApplicationChangementsBundle:Changements:checkuser" }
    options:
        expose: true
  
ajax_ticketint:
    pattern:  /ajaxticketint
    methods: POST|GET
    defaults: { _controller: "ApplicationChangementsBundle:Changements:TicketIntAjax" }
    
ajax_description:
    pattern:  /ajaxdescription
    methods: POST|GET
    defaults: { _controller: "ApplicationChangementsBundle:Changements:DescriptionAjax" }
    
ajax_ticketext:
    pattern:  /ajaxticketext
    methods: POST|GET
    defaults: { _controller: "ApplicationChangementsBundle:Changements:TicketExtAjax" }
    
changements_listbyprojet:
    pattern:  /changementsprj
    defaults: { _controller: ApplicationChangementsBundle:Changements:listByProjet }
 
changements_minicalendar:
    pattern:  /minicalendar
    defaults: { _controller: "ApplicationChangementsBundle:Changements:CalendarEvents" }
    options:
        expose: true
        
changements_showXhtml:
    pattern:  /{id}/showxhtml
    defaults: { _controller: "ApplicationChangementsBundle:Changements:showXhtml" }

changements_updatexhtml_changement:
    pattern:  /updatexhtml/
    defaults: { _controller: "ApplicationChangementsBundle:Changements:update_changement_status" }
    options:
        expose: true
 
changements_updatexhtml_favoris:
    pattern:  /updatefavorisxhtml/
    defaults: { _controller: "ApplicationChangementsBundle:Changements:update_changement_favoris" }
    options:
        expose: true
        

calendar_adesignajax_changements:
    methods: POST|GET
    pattern:  /adesignajaxchangements
    defaults: { _controller: "ApplicationChangementsBundle:AdesignCalendar:loadjqCalendarChangements" }
    options:
        expose: true  
 