#swiftmailer:
#    delivery_address: me@example.com
imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        firephp:
            type:  firephp
            level: info

#==================================================
#  ASSETIC
#==================================================

    
    #assets:
    #   bootstrap_css:
    #        inputs:
    #            - %kernel.root_dir%/../vendor/twitter/bootstrap/less/bootstrap.less
    #            - %kernel.root_dir%/../vendor/twitter/bootstrap/less/responsive.less
assetic:
    debug:          %kernel.debug%
    #pour le dev
    use_controller: true
    #bundles:        [ ]
    bundles:        [ ApplicationChangementsBundle,ApplicationCertificatsBundle,ApplicationRelationsBundle ]
    #bundles:        [ ApplicationChangementsBundle,SonataNewsBundle ]
    java: /usr/bin/java
    #java: "C:\ProgramFiles\Java\jre6\bin\java.exe"
    #java: "C:\\Program Files\\Java\\jre6\\bin\\java.exe"
    filters:
        cssrewrite: ~
       # cssembed:
        #    jar: %kernel.root_dir%/Resources/java/cssembed-0.4.5.jar
         #   apply_to: "\.css$|\.less$"
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
            apply_to: "\.css$"
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
       # closure:
      #      jar: %kernel.root_dir%/Resources/java/compiler.jar
    #    yui_css:
     #       jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        less:
            node: /usr/bin/node
            node_paths: [/opt/less/lib, /usr/lib/node_modules]
            apply_to: "\.less$"
#    assets:
#        fontawesome_css:
#          inputs:
#            - css/less/font-awesome.less
#          filters:
#            - less
#            - cssrewrite
#          output: css/cpfontawesome.css
#        fontawesome_IE7_css:
#          inputs:
#            - css/less/font-awesome-ie7.less
#          filters:
#            - less
#            - cssrewrite
#          output: css/cpfontawesome_IE7.css

services:
   twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
   twig.extension.debug:
       class:        Twig_Extension_Debug
       #class: Twig_Extensions_Extension_Debug
       tags:
           - { name: twig.extension }

swiftmailer:
  disable_delivery:  false
  # a remettre pour dev (pas denvoi de mail 
  #disable_delivery:  true
#swiftmailer:
#    delivery_address: me@example.com
