imports:
    - { resource: config.yml }

# In production environment you should know that the parameters for URL generation
# always pass the requirements. Otherwise it would break your link (or even site with
# strict_requirements = true). So we can disable the requirements check completely for
# enhanced performance with strict_requirements = null.
framework:
    router:
        strict_requirements: null

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
            
#==================================================
#  ASSETIC
#==================================================

    
    #assets:
    #   bootstrap_css:
    #        inputs:
    #            - %kernel.root_dir%/../vendor/twitter/bootstrap/less/bootstrap.less
    #            - %kernel.root_dir%/../vendor/twitter/bootstrap/less/responsive.less
assetic:
    debug:          %kernel.debug%
    #pour le dev
    use_controller: false
    #bundles:        [ ]
    bundles:        [ ApplicationChangementsBundle,ApplicationCertificatsBundle,ApplicationRelationsBundle ]
    #bundles:        [ ApplicationChangementsBundle,SonataNewsBundle ]
    #java: /usr/bin/java
    #java: "C:\ProgramFiles\Java\jre6\bin\java.exe"
    java: "C:\\Program Files\\Java\\jre6\\bin\\java.exe"
    filters:
        cssrewrite: ~
       # cssembed:
        #    jar: %kernel.root_dir%/Resources/java/cssembed-0.4.5.jar
         #   apply_to: "\.css$|\.less$"
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
            apply_to: "\.css$"
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
       # closure:
      #      jar: %kernel.root_dir%/Resources/java/compiler.jar
    #    yui_css:
     #       jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        less:
            node: /usr/bin/node
            node_paths: [/opt/less/lib, /usr/lib/node_modules]
            apply_to: "\.less$"
#    assets:
#        fontawesome_css:
#          inputs:
#            - css/less/font-awesome.less
#          filters:
#            - less
#            - cssrewrite
#          output: css/cpfontawesome.css
#        fontawesome_IE7_css:
#          inputs:
#            - css/less/font-awesome-ie7.less
#          filters:
#            - less
#            - cssrewrite
#          output: css/cpfontawesome_IE7.css

