<?php

namespace Application\ChangementsBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 * NotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangementsCommentsRepository extends EntityRepository{
//class ChangementsRepository extends EntityRepository{
 //use EventRepositoryTrait;
    public function myFindaAll() {
        return $this->createQueryBuilder('a')
                ->orderBy('id')
                        ->getQuery();

        //->getResult();
    }

    public function myFindAll() {
        return $this->createQueryBuilder('a')
                        ->leftJoin('a.idProjet', 'b')
                        ->leftJoin('a.idStatus', 'd')
                        ->leftJoin('a.demandeur', 'c')
                 ->leftJoin('a.idusers', 'e')
             //   ->groupby('e.nomUser')
                 ->add('orderBy', 'a.id DESC')
                        //   ->leftJoin('a.demandeur', 'c')
                        ->getQuery();
    }
    
public function getCommentsForChangement($changementId)
    {
        $qb = $this->createQueryBuilder('c')
                   ->select('c')
                   ->where('c.changement = :changement_id')
                    ->addOrderBy('c.created')
                   ->setParameter('changement_id', $changementId);

        
        return $qb->getQuery()
                  ->getResult();
    }
}

