<?php

namespace Application\ChangementsBundle\Entity;

use Doctrine\ORM\EntityRepository;


//use CalendR\Extension\Doctrine2\EventRepository as EventRepositoryTrait;
/**
 * NotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangementsStatusRepository extends EntityRepository {

    
}

