<?php

namespace Application\ChangementsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocchangementsRepository extends EntityRepository {

    public function myFindoldAll() {
        return $this->createQueryBuilder('a')
                        ->getQuery();

        //->getResult();
    }
 public function myFindAll() {
      //  return $this->createQueryBuilder('a')
        /*                ->leftJoin('a.idchangement', 'b')
                ->orderBy('a.id', 'DESC')
                        //   ->leftJoin('a.demandeur', 'c')
                        ->getQuery();
    }*/
 
        $query = $this->createQueryBuilder('a')
                ->select('a,b')
                ->add('orderBy', 'a.id DESC')
                ->leftJoin('a.idchangement', 'b');
                //  ->leftJoin($join, $alias, $conditionType)
              
        ;
        return $query->getQuery();

}
}