<?php

namespace Application\CertificatsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CertificatsFilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificatsFileTypeRepository extends EntityRepository {

  

}
