<?php

namespace Application\CertificatsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository {

    public function myFindaAll() {
        return $this->createQueryBuilder('a')
                        ->getQuery();

        //->getResult();
    }

  

}
