#==================================================
#  SONATA USERS
#==================================================
sonata_user:
    security_acl:     false
    class:
        user: Application\Sonata\UserBundle\Entity\User 
        group: Application\Sonata\UserBundle\Entity\Group
        
    profile:  # Profile Form (firstname, lastname, etc ...)
        form:
            type:               sonata_user_profile
            handler:            sonata.user.profile.form.handler.default
            name:               sonata_user_profile_form
            validation_groups:  [Profile]   
    admin:                  # Admin Classes
        user:
            class:          Sonata\UserBundle\Admin\Entity\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

        group:
            class:          Sonata\UserBundle\Admin\Entity\GroupAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
  
        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]
  
        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:
  
        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:
        
   
parameters:
    sonata.user.admin.user.class: Application\Sonata\UserBundle\Admin\UserAdmin