#==================================================
#  SONATA ADMIN
#==================================================

            #
# more information can be found here http://sonata-project.org/bundles/admin
#
sonata_admin:
    security:
        handler: sonata.admin.security.handler.role
    title:                Adm Sonata
    title_logo:           bundles/sonataadmin/logo_title.png
    templates:
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
        history: SonataAdminBundle:CRUD:history.html.twig
        preview: SonataAdminBundle:CRUD:preview.html.twig
        delete:  SonataAdminBundle:CRUD:delete.html.twig
        batch:   SonataAdminBundle:CRUD:list__batch.html.twig
        acl:     SonataAdminBundle:CRUD:acl.html.twig
        action:  SonataAdminBundle:CRUD:action.html.twig
        select:  SonataAdminBundle:CRUD:list__select.html.twig
        filter:  SonataAdminBundle:Form:filter_admin_fields.html.twig
        dashboard:           SonataAdminBundle:Core:dashboard.html.twig
        search:              SonataAdminBundle:Core:search.html.twig
        batch_confirmation:  SonataAdminBundle:CRUD:batch_confirmation.html.twig
        inner_list_row:      SonataAdminBundle:CRUD:list_inner_row.html.twig
        base_list_field:     SonataAdminBundle:CRUD:base_list_field.html.twig
        list_block:          SonataAdminBundle:Block:block_admin_list.html.twig
        user_block:          SonataAdminBundle:Core:user_block.html.twig
        add_block:           SonataAdminBundle:Core:add_block.html.twig
        pager_links:         SonataAdminBundle:Pager:links.html.twig
        pager_results:       SonataAdminBundle:Pager:results.html.twig
        history_revision_timestamp:  SonataAdminBundle:CRUD:history_revision_timestamp.html.twig
        short_object_description:    SonataAdminBundle:Helper:short-object-description.html.twig
        search_result_block: SonataAdminBundle:Block:block_search_result.html.twig

    options:
        html5_validate:                         true      # use html5 validation
        confirm_exit:                           true      # enabled confirmation when quitting with unsaved changes
        use_select2:                            true      # enable select2
        use_icheck:                             true      # enable iCheck
        dropdown_number_groups_per_colums:      2         # max items per column in dropdown menu (add button in top nav)
        title_mode:           'both'                      # 'both', 'single_text' or 'single_image'
        
    assets:
        stylesheets:

            # Defaults:
            - bundles/sonataadmin/admin-lte/css/bootstrap.min.css
            - bundles/sonataadmin/admin-lte/css/font-awesome.min.css
            - bundles/sonataadmin/admin-lte/css/ionicons.min.css
            - bundles/sonataadmin/admin-lte/css/AdminLTE.css
            - bundles/sonatajquery/themes/flick/jquery-ui-1.10.4.custom.css
            - bundles/sonataadmin/select2/select2.css
            - bundles/sonataadmin/select2/select2-bootstrap.css
            - bundles/sonataadmin/bootstrap3-editable/bootstrap3-editable/css/bootstrap-editable.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css
        javascripts:

            # Defaults:
            - bundles/sonatajquery/jquery-1.10.2.js
            - bundles/sonatajquery/jquery-ui-1.10.4.js
            - bundles/sonatajquery/jquery-ui-i18n.js
            - bundles/sonataadmin/jquery/jquery.form.js
            - bundles/sonataadmin/jquery/jquery.confirmExit.js
            - bundles/sonataadmin/admin-lte/js/bootstrap.min.js
            - bundles/sonataadmin/bootstrap3-editable/bootstrap3-editable/js/bootstrap-editable.min.js
            - bundles/sonataadmin/select2/select2.min.js
            - bundles/sonataadmin/App.js
            - bundles/sonataadmin/Admin.js

   

