<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\EpostBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOS\CommentBundle\Entity\Comment as BaseComment;
/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */

/**
 * @ORM\Table(name="epost_commentsthread")
 * @ORM\Entity
 *
 * @ORM\ChangeTrackingPolicy("DEFERRED_EXPLICIT")
 */
class EpostCommentsThread extends BaseComment
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * Thread of this comment
     *
     * @var Thread
     * 
     * @ORM\ManyToOne(targetEntity="EpostThread")
     *   @ORM\JoinColumn(name="thread_id", referencedColumnName="id")
     */
    protected $thread;

     /**
     * @var \Application\Sonata\UserBundle\Entity\User
     *
     * @ORM\ManyToOne(targetEntity="Application\Sonata\UserBundle\Entity\User")
     * @ORM\OrderBy({"username" = "ASC"})
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="user", referencedColumnName="id")
     * })
     */
    private $user;
      
    /**
     * @ORM\ManyToOne(targetEntity="Epost", inversedBy="commentsthread")
     * @ORM\JoinColumn(name="epost_id", referencedColumnName="id")
     */
    protected $epost;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

   
    /**
     * Set user
     *
     * @param \Application\Sonata\UserBundle\Entity\User $user
     * @return EpostCommentsThread
     */
    public function setUser(\Application\Sonata\UserBundle\Entity\User $user = null)
    {
        $this->user = $user;
    
        return $this;
    }

    /**
     * Get user
     *
     * @return \Application\Sonata\UserBundle\Entity\User 
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set epost
     *
     * @param \Application\EpostBundle\Entity\Epost $epost
     * @return EpostCommentsThread
     */
    public function setEpost(\Application\EpostBundle\Entity\Epost $epost = null)
    {
        $this->epost = $epost;
    
        return $this;
    }

    /**
     * Get epost
     *
     * @return \Application\EpostBundle\Entity\Epost 
     */
    public function getEpost()
    {
        return $this->epost;
    }
}