_changements:
    resource: "@ApplicationChangementsBundle/Resources/config/routing/changements.yml"
    prefix:   /

_changements_contact:
    resource: "@ApplicationChangementsBundle/Resources/config/routing/changementsContact.yml"
    prefix:   /contact
    
_changements_ajax_operations:
    resource: "@ApplicationChangementsBundle/Resources/config/routing/changementsajax.yml"
    prefix:   /
    
_changements_fichiers:
    resource: "@ApplicationChangementsBundle/Resources/config/routing/changementsupload.yml"
    prefix:   /
    
_changements_comments:
    resource: "@ApplicationChangementsBundle/Resources/config/routing/changementscomments.yml"
    prefix:   /changements/comments
    
_docchangements:
    resource: "@ApplicationChangementsBundle/Resources/config/routing/docchangements.yml"
    prefix:   /docchangements
    #prefix:   /admin/tag
