<?php

namespace Application\RelationsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChronoAbsencesRepository extends EntityRepository {

      public function myFindAll() {
        return $this->createQueryBuilder('a')
                        ->select('a,b')
                        ->add('orderBy', 'a.nom ASC')
                        ->leftJoin('a.user', 'b')
                        ->getQuery();

        //->getResult();
    }
     public function myFindId($id) {
        $parameters = array();
        $values = array('a,partial c.{id,nomUser}');

        $query = $this->createQueryBuilder('a')
                ->select($values)
                 ->leftJoin('a.user', 'c');
                
        $query->add('orderBy', 'a.id DESC')
                ->andwhere('a.id = :myid');
        $query->setParameter('myid', $id);
    return $query->getQuery()->getSingleResult();
    }
}
