<?php

namespace Application\RelationsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentbbRepository extends EntityRepository {

    public function myFindAll() {
        return $this->createQueryBuilder('a')
                     ->select('a,b')
                
                ->leftJoin('a.idprojet', 'b')
                ->add('orderBy', 'a.id DESC')
                
                        ->getQuery();

        //->getResult();
    }

   

}
