<?php

namespace Application\RelationsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends EntityRepository {

    public function myFindAll() {
        return $this->createQueryBuilder('a')
                        ->select('a,b')
                        ->add('orderBy', 'a.nomprojet ASC')
                        ->leftJoin('a.picture', 'b')
                        ->getQuery();

        //->getResult();
    }

    public function getProjetForRequeteBuilder() {
        $query = $this->createQueryBuilder('a')
                //  ->select('partial a.{id,nomprojet}')
                ->select('a')
                ->leftJoin('a.idchangement', 'b')
                ->Where('b.id IS NOT NULL')
                ->add('orderBy', 'a.nomprojet ASC')
        ;
        return $query;
    }

}
