<?php

namespace Application\RelationsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServeursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServeursRepository extends EntityRepository
{
      public function myFindAll() {
        return $this->createQueryBuilder('a')
                  ->select('a,b,c')
                        ->leftJoin('a.idzone', 'b')
                        ->leftJoin('a.idsite', 'c')
                        ->leftJoin('a.id_env', 'd')
                      /*  ->leftJoin('a.idStatus', 'd')
                        ->leftJoin('a.picture', 'f')*/
                        ->orderBy('a.id')
                        ->getQuery();

        //->getResult();
    }
}
