<?php

namespace Application\ADesigns\CalendarBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */ 
class MyEventsCalendarRepository extends EntityRepository{

   
}