var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Dim",
            "mon": "lun",
            "tue": "Mar",
            "wed": "Mer",
            "thu": "Jeu",
            "fri": "Ven",
            "sat": "Sam",
            "jan": "Jan",
            "feb": "Fev",
            "mar": "Mar",
            "apr": "Avr",
            "may": "Mai",
            "jun": "Jun",
            "jul": "Jul",
            "aug": "Aou",
            "sep": "Sep",
            "oct": "Oct",
            "nov": "Nov",
            "dec": "Dec"
        },
        "no_implemented": "No implemented yet",
        "to_date_view": "Click to the view of current date",
        "i_undefined": "Undefined",
        "allday_event": "All day event",
        "repeat_event": "Repeat event",
        "time": "Time",
        "event": "Event",
        "location": "Location",
        "participant": "Participant",
        "get_data_exception": "Exception when getting data",
        "new_event": "New event",
        "confirm_delete_event": "Do you confirm to delete this event? ",
        "confrim_delete_event_or_all": "Do you want to all repeat events or only this event? \r\nClick [OK] to delete only this event, click [Cancel] delete all events",
        "data_format_error": "Data format error! ",
        "invalid_title": "Event title can not be blank or contains ($<>)",
        "view_no_ready": "View is not ready",
        "example": "ex., rendez-vous mon bureau",
        "content": "What",
        "create_event": "Creer Evenement",
        "update_detail": "Editer cet enregistrement",
        "click_to_detail": "Voir cet enregistrement",
        "i_delete": "Supprimer",
        "day_plural": "Jours",
        "others": "Others",
        "item": ""
    }
});
