<?php

namespace Application\CertificatsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificatsCenterRepository extends EntityRepository {

    public function myFindAll() {
        return $this->createQueryBuilder('a')
                        ->getQuery();

        //->getResult();
    }

    public function myFindaAll() {
        return $this->createQueryBuilder('a')
                ->select(array('a,b,c'))
               
                        ->leftJoin('a.project', 'b')
                        ->leftJoin('a.typeCert', 'c')
                        ->orderBy('a.id', 'DESC') 
                        ->getQuery();
    }

}
