<?php

namespace Application\CertificatsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CertificatsFilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificatsFilesRepository extends EntityRepository {

    public function myFindAll($id = null) {
        //$values = array('a,partial b.{id,fileName,project}');
        $values = array('a,b,c');
        $query = $this->createQueryBuilder('a')
                ->select($values)
                ->leftJoin('a.certificats', 'b')
                ->leftJoin('b.project', 'c')
                ->orderBy('a.id', 'DESC');
        if (isset($id)) {
            $query->andwhere('b.id = :myid');
            $query->setParameter('myid', $id);
        }
        return $query;
        //  return $query->getQuery();
    }

}
