<?php

namespace Application\CertificatsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CertificatsFilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificatsFilesRepository extends EntityRepository
{
}
