<?php

namespace Application\MyNotesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotesCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotesCategoriesRepository extends EntityRepository
{
}
