_calendar_adesigncalendar:
    resource: "@ApplicationCalendarBundle/Resources/config/routing/adesigncalendar.yml"
    prefix:   /adesigncalendar
_calendar_adesignctegories:
    resource: "@ApplicationCalendarBundle/Resources/config/routing/calendarevenements.yml"
    prefix:   /categoriescalendar

_calendar_rootcalendar:
    resource: "@ApplicationCalendarBundle/Resources/config/routing/calendarroot.yml"
    prefix:   /allcalendar