<?php

namespace Application\CalendarBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdesignCalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdesignCalendarRootRepository extends EntityRepository {

    public function myFindAll($id_owner = null, $user_groups = array()) {

        //var_dump($user_groups);

        $parameters = array();
        $values = array('a,b,c');
        $query = $this->createQueryBuilder('a')
                ->select($values)
                //   ->distinct('a.id')
                ->leftJoin('a.owner', 'b')
                ->leftJoin('a.groupedit', 'c');
        /* ------------------------------------
         * Filtrage par user
          ----------------------------------- */

        if (isset($id_owner)) {
            $query->where('b.id = :idOwner')
                    ->setParameter('idOwner', $id_owner);
        }
        /* ------------------------------------
         * Filtrage par groupes
          ----------------------------------- */

        if (isset($user_groups)) {
            $query->orWhere('c.id IN (:idGroupes)')
                    ->setParameter('idGroupes', $user_groups);
        }
        return $query->getQuery()->getResult();
    }

}
