<?php

namespace Application\CalendarBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdesignCalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdesignCalendarRepository extends EntityRepository {

    
     public function myFindaIdAll($id) {
 /*       $parameters = array();
        $values = array('a,partial b.{id,nomprojet},partial c.{id,nomUser},partial d.{id,nom,description},f,h');

        
    if (!$entity) {
                throw $this->createNotFoundException('Unable to find ChangementsContact entity.');
            }
            $ret['IsSuccess'] = true;
            $ret['Msg'] = 'update success';
            $data['id'] = $entity->getId();
            $entity->getBgColor(); //set the background color of the event's label
            $data['allDay'] = (boolean) $entity->getAllDay();
             $data['title'] = $entity->getTitle();
            $data['start'] = $entity->getstartDatetime()->format('Y-m-d H:i:s');
             $data['end']  = $entity->getendDatetime()->format('Y-m-d H:i:s');
          
            $data['className'] = $entity->getCssClass();
            $data['backgroundColor'] = $entity->getBgColor();
            $data['description'] = $entity->getDescription();
            $data['textColor'] = $entity->getFgColor(); //set the foregr
            $ret['data'] = $data;
 */
}

}