<?php

namespace Application\CalendarBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarGroupRepository extends EntityRepository {

    public function myFindAll($id_user = null,$groupes='mongroupe') {

        $values = array('a,b,c');
        $query = $this->createQueryBuilder('a')
                ->select($values)
                ->leftJoin('a.owner', 'b')
                  ->leftJoin('a.users', 'c');
            
       if (isset($id_user)) {
            $query->where('b.id = :idUser')
                    ->setParameter('idUser', $id_user);
        }

        
      if (isset($groupes)) {
            $query->orWhere('c.id IN (:idUsera)')
                    ->setParameter('idUsera', $id_user);
      }
        return $query->getQuery()->getResult();
    }
    
    
      public function myFindInGroupAll($id_user = null) {

        $values = array('a,b,c');
        $query = $this->createQueryBuilder('a')
                ->select($values)
                ->leftJoin('a.owner', 'b')
                  ->leftJoin('a.users', 'c')
     ->where('c.id IN (:idUsera)')
                    ->setParameter('idUsera', $id_user);
        
        return $query->getQuery()->getResult();
    }

}
