<?php

namespace Application\CalendarBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * CalendarEvenementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarEvenementsRepository extends EntityRepository {


}

