parameters:
#    application_my_notes.example.class: Application\MyNotesBundle\Example

services:
#    application_my_notes.example:
#        class: %application_my_notes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
