<?php

namespace Application\RelationsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServeursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServeursRepository extends EntityRepository
{
}
