<?php

namespace Application\RelationsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServeursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServeursRepository extends EntityRepository
{
      public function myFindAll() {
        return $this->createQueryBuilder('a')
                ->select()
                       /* ->leftJoin('a.idProjet', 'b')
                        ->leftJoin('a.demandeur', 'c')
                        ->leftJoin('a.idStatus', 'd')
                        ->leftJoin('a.picture', 'f')*/
                        ->orderBy('a.id')
                        ->getQuery();

        //->getResult();
    }
}
