calendar_adesignajax:
    methods: POST|GET
    pattern: /adesignajax
    defaults: { _controller: "ApplicationCalendarBundle:Calendar:loadjqCalendar" }
    options:
        expose: true


calendar_adesignajax_edit:
    methods: POST|GET
    pattern: /{id}/editadesignajax
    defaults: { _controller: "ApplicationCalendarBundle:Calendar:editajaxCalendar" }
    options:
        expose: true
        
calendar_adesignajax_getevent:
    methods: POST|GET
    pattern: /geteventadedesignajax
    defaults: { _controller: "ApplicationCalendarBundle:Calendar:getEventCalendar" }
    options:
        expose: true


calendar_adesignajax_update:
    methods: POST|GET
    pattern: /{id}/updateadesignajax
    defaults: { _controller: "ApplicationCalendarBundle:Calendar:updateajaxCalendar" }
    options:
        expose: true
        
        
calendar_dropajax:
    methods: POST|GET
    pattern: /updateajax
    defaults: { _controller: "ApplicationCalendarBundle:Calendar:updatejqCalendar" }
    options:
        expose: true
        
calendar_indexadesign:
    pattern: /
    defaults: { _controller: "ApplicationCalendarBundle:Calendar:indexadesign" }
    methods: POST|GET
 
            
calendar_dashboard:
    pattern: /dashboard
    defaults: { _controller: "ApplicationCalendarBundle:Calendar:dashboard" }
    methods: POST|GET
    
calendar_userootcalendar:
    pattern: /usecalendar
    defaults: { _controller: "ApplicationCalendarBundle:Calendar:usecalendar" }
    methods: POST|GET
    