calendar_adesignajax:
    methods: POST|GET
    pattern:  /adesignajax
    defaults: { _controller: "ApplicationCalendarBundle:Calendar:loadjqCalendar" }
    options:
        expose: true

calendar_adesign_edit:
    pattern:  /{id}adesignedit
    defaults: { _controller: "ApplicationCalendarBundle:Calendar:editajaxCalendar" }
    options:
        expose: true
        
calendar_dropajax:
    methods: POST|GET
    pattern:  /updateajax
    defaults: { _controller: "ApplicationCalendarBundle:Calendar:updatejqCalendar" }
    options:
        expose: true
        
calendar_indexadesign:
    pattern:  /
    defaults: { _controller: "ApplicationCalendarBundle:Calendar:indexadesign" }
    methods: POST|GET
 
            
calendar_dashboard:
    pattern:  /dashboard
    defaults: { _controller: "ApplicationCalendarBundle:Calendar:dashboard" }
    methods: POST|GET
    
calendar_userootcalendar:
    pattern:  /usecalendar
    defaults: { _controller: "ApplicationCalendarBundle:Calendar:usecalendar" }
    methods: POST|GET
    
     
     
 
