<?php

namespace Application\ChangementsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangementsContactRepository extends EntityRepository {

    public function myFindAll() {
        return $this->createQueryBuilder('a')
                ->select('a')
             
                        ->getQuery();
        //->getResult();
    }

    
}
