absences:
    pattern:  /
    defaults: { _controller: "ApplicationRelationsBundle:ChronoAbsences:index" }

absences_calendrier:
    pattern:  /calendrier
    defaults: { _controller: "ApplicationRelationsBundle:ChronoAbsences:calendrierAbsences" }


absences_new:
    pattern:  /new
    defaults: { _controller: "ApplicationRelationsBundle:ChronoAbsences:new" }

absences_create:
    pattern:  /create
    defaults: { _controller: "ApplicationRelationsBundle:ChronoAbsences:create" }
    requirements: { _method: post }

absences_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ApplicationRelationsBundle:ChronoAbsences:edit" }

absences_update:
    pattern:  /{id}/update
    defaults: { _controller: "ApplicationRelationsBundle:ChronoAbsences:update" }
    requirements: { _method: post|put }

absences_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ApplicationRelationsBundle:ChronoAbsences:delete" }
    requirements: { _method: post|delete }
    
calendar_adesignajax_absences:
    methods: POST|GET
    pattern:  /adesignajaxabsences
    defaults: { _controller: "ApplicationRelationsBundle:ChronoAbsences:loadjqCalendarAbscences" }
    options:
        expose: true  
 
calendar_createajax_absences:
    methods: POST|GET
    pattern:  /creteajaxabsence
    defaults: { _controller: "ApplicationRelationsBundle:ChronoAbsences:createjqCalendar" }
    options:
       expose: true  
       
calendar_updateajax_absences:
    methods: POST|GET
    pattern:  /updateajaxabsence
    defaults: { _controller: "ApplicationRelationsBundle:ChronoAbsences:updatejqCalendar" }
    options:
       expose: true  