<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\EservicesBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Mapping\ClassMetadata;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Application\EservicesBundle\Entity\Eproduit;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */

/**
 * Changements
 *
 * @ORM\Table(name="eproduits_history")
 * @ORM\Entity(repositoryClass="Application\EservicesBundle\Repository\EproduitHistoryRepository")
  * @ORM\HasLifecycleCallbacks()
  */
class EproduitHistory {

  //  protected $comments = array();
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * Get id
     *
     * @return integer 
     */

   
      /**
     * @var datetime $dateIn
     *
     * @ORM\Column(name="date_in", type="datetime")
     */
    protected $dateIn;
    /**
     * @var datetime $dateOut
     *
     * @ORM\Column(name="date_out", type="datetime")
     */
    protected $dateOut;

    /**
     * @var \Application\Sonata\UserBundle\Entity\User
     *
     * @ORM\ManyToOne(targetEntity="Application\Sonata\UserBundle\Entity\User")
     * @ORM\OrderBy({"username" = "ASC"})
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="preteur", referencedColumnName="id")
     * })
     */
    private $preteur;

    /**
     * @var Application\EserviceBundle\Entity\Eproduit
     *
     * @ORM\ManyToOne(targetEntity="Application\EservicesBundle\Entity\Eproduit",cascade={"remove"})
     * @ORM\OrderBy({"name" = "ASC"})
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="produit", referencedColumnName="id")
     * })
     */
    private $produit;
    
     /**
     * @var \Application\Sonata\UserBundle\Entity\User
     *
     * @ORM\ManyToOne(targetEntity="Application\Sonata\UserBundle\Entity\User")
     * @ORM\OrderBy({"username" = "ASC"})
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="emprunteur", referencedColumnName="id")
     * })
     */
    private $emprunteur;
    
   
   


    public function getId() {
        return $this->id;
    }

   public function __toString() {
        return $this->getId();
    }

   
    /**
     * Constructor
     */
    public function __construct() {
     //   $this->history = new \Doctrine\Common\Collections\ArrayCollection();
        $this->setDateIn(new \DateTime());
        $this->setDateOut(new \DateTime());
    }

    /**
     * Set dateIn
     *
     * @param \DateTime $dateIn
     * @return EproduitHistory
     */
    public function setDateIn($dateIn)
    {
        $this->dateIn = $dateIn;
    
        return $this;
    }

    /**
     * Get dateIn
     *
     * @return \DateTime 
     */
    public function getDateIn()
    {
        return $this->dateIn;
    }

    /**
     * Set dateOut
     *
     * @param \DateTime $dateOut
     * @return EproduitHistory
     */
    public function setDateOut($dateOut)
    {
        $this->dateOut = $dateOut;
    
        return $this;
    }

    /**
     * Get dateOut
     *
     * @return \DateTime 
     */
    public function getDateOut()
    {
        return $this->dateOut;
    }

    /**
     * Set preteur
     *
     * @param \Application\Sonata\UserBundle\Entity\User $preteur
     * @return EproduitHistory
     */
    public function setPreteur(\Application\Sonata\UserBundle\Entity\User $preteur = null)
    {
        $this->preteur = $preteur;
    
        return $this;
    }

    /**
     * Get preteur
     *
     * @return \Application\Sonata\UserBundle\Entity\User 
     */
    public function getPreteur()
    {
        return $this->preteur;
    }

    /**
     * Set emprunteur
     *
     * @param \Application\Sonata\UserBundle\Entity\User $emprunteur
     * @return EproduitHistory
     */
    public function setEmprunteur(\Application\Sonata\UserBundle\Entity\User $emprunteur = null)
    {
        $this->emprunteur = $emprunteur;
    
        return $this;
    }

    /**
     * Get emprunteur
     *
     * @return \Application\Sonata\UserBundle\Entity\User 
     */
    public function getEmprunteur()
    {
        return $this->emprunteur;
    }

    /**
     * Set produit
     *
     * @param \Application\EservicesBundle\Entity\Eproduit $produit
     * @return EproduitHistory
     */
    public function setProduit(\Application\EservicesBundle\Entity\Eproduit $produit = null)
    {
        $this->produit = $produit;
    
        return $this;
    }

    /**
     * Get produit
     *
     * @return \Application\EservicesBundle\Entity\Eproduit 
     */
    public function getProduit()
    {
        return $this->produit;
    }
    
    
     
     /**
* Set name
*
* @param string $preteur
* @return Preteur
*/
    public function setcPreteur($preteur) {
        $this->preteur = $preteur;

        return $this;
    }

    /**
* Get preteur
*
* @return string
*/
    public function getcPreteur() {
        return $this->preteur;
    }

}